### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [csinkers/ualbion#2]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this port in the README. Even early screenshots are fine!

**Comment by csinkers** [comment]
Done.

**Comment by neuromancer** [comment]
Wow, it looks like a playable game!, how far you can get with the current code?

**Comment by csinkers** [comment]
You can walk around, and move things about in your inventory but you can't interact with the environment much yet. Still a lot to do, e.g.:

- audio subsystem, file formats are known, but the music is in the old XMI format which is difficult to play without artifacts. Can convert to MIDI, but some notes skip etc and the instruments don't match up too well.
- handling all the event chains that are baked into the maps which define a lot of the gameplay
- adding a conversation system (the GUI system it will be built on is mostly done at least)
- implementing the combat system (huge job, will require lots of reverse engineering)
- wide variety of miscellaneous gameplay behaviours
- loading and saving of saved games. Currently most of the loaders are only one-way, need to convert them so they can write as well as read.

Main goal is to improve the interface and make some visual improvements, the original game was very clicky so I'd like to add some pathfinding and a more efficient way of examining and manipulating objects.

**Comment by neuromancer** [comment]
If you have a minute, please update the README to explain the current status (copying and pasting this looks fine to me). Keep up the hard work!
