### ISSUE TITLE
Hang in loadgame dialog

### ISSUE THREAD

**Issue by lucorp** [csinkers/ualbion#23]
When loading game from main menu and no saved games are present, the dialog hangs. ESC will produce error in screenshot.

OS: Xubuntu 20.04

![image](https://user-images.githubusercontent.com/4839225/113592485-8690c600-9635-11eb-8496-eb61e124a784.png)

**Comment by csinkers** [comment]
Yeah, saving and loading is still a work in progress. I'll improve it once I get map editing done and decode the details of NPC state.

**Comment by csinkers** [comment]
This should be fixed now, saved games will now load and the load game dialog can be closed via pressing Escape or right-clicking on it.

**Comment by lucorp** [comment]
Right click tested and working in Linux
