### ISSUE TITLE
Alternative Albion re-implementations

### ISSUE THREAD

**Issue by neuromancer** [csinkers/ualbion#3]
The only Albion re-implementation I could find is [FreeAlbion](https://github.com/freealbion/freealbion). I wonder if that could help to speed-up the development of this one.

**Comment by csinkers** [comment]
Yup, aware of that one - the wiki info was very helpful for the file formats. There's also the statically recompiled version at https://github.com/M-HT/SR which is handy as it lets you effectively run the original on windows without dosbox, letting you use all the nice RE tools like ETW tracing, windbg and ghidra.
