### ISSUE TITLE
Demo support?

### ISSUE THREAD

**Issue by neuromancer** [csinkers/ualbion#7]
It looks like there is an [Albion demo](https://archive.org/details/Albidemo) that can be freely (and probably legally) downloaded to test UAlbion. Is there any plans to support it?

**Comment by csinkers** [comment]
Just tried it out, and wow... that was way easier than I was expecting. The demo's MAIN.EXE is byte-for-byte the same as the released one, only difference is a bunch of data has been removed from the XLDs (e.g. all the maps except what's required for the demo, and I assume any textures etc that aren't needed for those levels).

So as far as I can tell, the demo is currently every bit as supported as the full version at this point. Once I start adding more gameplay logic I'll have to add a couple of things, but from what I've seen in the data so far, there's basically just one main "IsDemo" setting that various event triggers check, so it shouldn't be a big deal.
